Loading pytorch-gpu/py3/1.10.1
  Loading requirement: cuda/11.2 nccl/2.9.6-1-cuda cudnn/8.1.1.33-cuda gcc/8.4.1
    openmpi/4.1.1-cuda intel-mkl/2020.4 magma/2.5.4-cuda sox/14.4.2
+ srun python plug_ai/main.py --config_file ./config_exemples/config_Brats.yaml --mode Inference
Initialize training...
Final config: {'mode': 'Inference', 'model_name': 'model_test', 'dataset_dir': '/gpfswork/rech/ibu/commun/BraTS2021/BraTS2021_Training_Data/', 'task': 'THIS IS A TEST', 'categories': ['cat0', 'cat1', 'cat2', 'cat3', 'cat4'], 'limit_sample': 20, 'batch_size': 2, 'nb_epoch': 1, 'learning_rate': '5e-05', 'device': 'cuda', 'random_seed': 2022, 'verbose': 'Full', 'export_config': False, 'report_log': False, 'checkpoints_path': './checkpoints', 'model_type': 'DynUnet', 'model_args': None, 'model_kwargs': None, 'res_out': False, 'config_file': './config_exemples/config_Brats.yaml'}
Arguments initialized
loading dataset...
got datalist, extract: 
 {'channel_0': '/gpfswork/rech/ibu/commun/BraTS2021/BraTS2021_Training_Data/BraTS2021_00081/BraTS2021_00081_flair.nii.gz', 'channel_1': '/gpfswork/rech/ibu/commun/BraTS2021/BraTS2021_Training_Data/BraTS2021_00081/BraTS2021_00081_t1ce.nii.gz', 'channel_2': '/gpfswork/rech/ibu/commun/BraTS2021/BraTS2021_Training_Data/BraTS2021_00081/BraTS2021_00081_t2.nii.gz', 'channel_3': '/gpfswork/rech/ibu/commun/BraTS2021/BraTS2021_Training_Data/BraTS2021_00081/BraTS2021_00081_t1.nii.gz', 'label': '/gpfswork/rech/ibu/commun/BraTS2021/BraTS2021_Training_Data/BraTS2021_00081/BraTS2021_00081_seg.nii.gz'}
Dataset loaded
checking model exists
loading DynUnet model
Model loaded
INFERENCE MODE
Execution initialised
Inference Mode
start inference loop, 10 steps
WARNING, the inference will probably cause an OOM
Inference_step 1/10
Inference_step 2/10
Inference_step 3/10
Inference_step 4/10
Inference_step 5/10
Inference_step 6/10
Inference_step 7/10
Inference_step 8/10
Inference_step 9/10
Inference_step 10/10
>>> Complete execution in: 0:00:13.540567
